# Generated by Django 6.0.3 on 2026-04-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sentiment',
            field=models.CharField(default='Aniqlanmadi', max_length=20),
        ),
        migrations.AddField(
            model_name='comment',
            name='sentiment_foiz',
            field=models.FloatField(default=0.0),
        ),
    ]
