# Generated by Django 6.0.3 on 2026-04-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingattempt',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phishingattempt',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phishingattempt',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phishingattempt',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phishingattempt',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='phishingattempt',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='phishingattempt',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
