# Generated by Django 6.0.3 on 2026-04-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_phishingattempt_city_phishingattempt_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingattempt',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='phishingattempt',
            name='platform',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phishingattempt',
            name='screen_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='phishingattempt',
            name='timezone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
